version: "3.8"

services:
  postgres:
    image: postgres:11.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /:/var/lib/postgresql/data

volumes:
  postgres: null
